# Local development profile properties
# LOGS_PATH here ensures local file logs go into ./logs by default
LOGS_PATH=./logs

# You can override log levels for local debugging if desired
logging.level.org.springframework=DEBUG
logging.level.com.example.traning=DEBUG
