spring.application.name=TraningApp

# JPA設定（MySQL用）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL接続設定
# local環境用
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#GCP環境用
# spring.datasource.url=jdbc:mysql://127.0.0.1:3306/training_db?serverTimezone=Asia/Tokyo
# spring.datasource.username=springuser
# spring.datasource.password=password
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=@db.url@
spring.datasource.username=@db.username@
spring.datasource.password=@db.password@
spring.datasource.driver-class-name=@db.driver-class-name@
# Doma2設定
doma.dialect=mysql

# バッチ設定
# batch.master.update.file-path=/Users/fujinoikki/Desktop/java_app/TraningApp/input/master_data.csv
batch.master.update.file-path=/home/fighterkazu_0807/input/master_data.csv
batch.master.update.cron=0 30 15 * * *
batch.master.tokenCleanup.cron=0 0 0 * * *
# batch.master.update.cron=0 * * * * *

# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:your-gmail-address@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email